apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: MyApp
  labels:
    app: MyApp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: MyApp
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70