apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  replicas: 1
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:alpine
        ports:
          - containerPort: 6379
        volumeMounts:
          - name: redis-data
            mountPath: /data
        ## Resources                   
        resources:
          limits:
            memory: "256Mi"  
            cpu: "200m"      
          requests:
            memory: "128Mi"
            cpu: "100m" 
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 500Mi
