apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # Environment Variables
  user: dXNyLWFwcA==
  user_password: YWRhLWRiLXBhc3N3b3Jk
  root_password: YWRhLWRiLXBhc3N3b3Jk