apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: mysql-svc
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root_password
        - name: MYSQL_DATABASE
          value: db-myapp
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user_password
        ports:      
          - containerPort: 3306
        resources:
          limits:
            memory: "512Mi"  
            cpu: "400m"      
          requests:
            memory: "128Mi"
            cpu: "100m"
        #volumeMounts:
        #  - name: mysql-data
        #    mountPath: /var/lib/mysql
      #volumes:
      #- name: mysql-data
      #  persistentVolumeClaim:
      #    claimName: mysql-pvc

