name: Pipeline-Laravel

on: workflow_dispatch
     
jobs:
  tagging_repo: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: '0'        
    # Set jobs taggind repository here

  security_img_scan:
    runs-on: ubuntu-latest
    needs: [tagging_repo]
              
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build images 
        run: |
          docker build -t docker.io/${{ secrets.DOCKER_USERNAME }}/laravel-app:${{ github.sha }} -f ./gitops/build/Dockerfile .
   
      - name: Security scan
        uses: docker://aquasec/trivy:0.19.2
        with:
          args: --exit-code 1 --severity HIGH,CRITICAL docker.io/${{ secrets.DOCKER_USERNAME }}/laravel-app:${{ github.sha }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          #severity: 'CRITICAL,HIGH'
        continue-on-error: true  

  build_and_push:
    needs: security_img_scan
    runs-on: ubuntu-latest
       
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker meta latest
        id: metalatest
        uses: docker/metadata-action@v5
        with:
          images: |
            laravel-app
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Docker meta sha
        id: metasha
        uses: docker/metadata-action@v5
        with:
          images: |
            laravel-app
          tags: |
            type=sha,prefix=v-{{sha}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        id: docker_login
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push laravel app image main
        uses: docker/build-push-action@v5
        id: docker_build_sha
        with:
          context: .
          file: ./gitops/build/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: true
          labels: ${{ steps.metasha.outputs.labels }}
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/${{ steps.metasha.outputs.tags }}

      - name: Build and push  image
        uses: docker/build-push-action@v5
        id: docker_build_latest
        with:
          context: .
          file: ./gitops/build/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: true
          labels: ${{ steps.metalatest.outputs.labels }}
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/${{ steps.metalatest.outputs.tags }}

      - name: Use output version latest
        id: output-version-latest
        run: echo ${{ steps.metalatest.outputs.tags }}            

      - name: Use output version sha
        id: output-version-sha
        run: echo ${{ steps.metasha.outputs.tags }}          